begin;

create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user() cascade;
drop function if exists public.set_updated_at() cascade;
drop function if exists public.guard_profile_updates() cascade;
drop function if exists public.is_role(text[]) cascade;
drop function if exists public.notify_students_about_drive() cascade;
drop function if exists public.seed_demo_account(uuid, text, text, text, text, text, text, text, text, text[]) cascade;

drop table if exists public.aptitude_attempts cascade;
drop table if exists public.aptitude_tests cascade;
drop table if exists public.placement_notifications cascade;
drop table if exists public.placement_applications cascade;
drop table if exists public.placement_drives cascade;
drop table if exists public.semester_results cascade;
drop table if exists public.courses cascade;
drop table if exists public.research_papers cascade;
drop table if exists public.audit_logs cascade;
drop table if exists public.activities cascade;
drop table if exists public.student_skills cascade;
drop table if exists public.student_goals cascade;
drop table if exists public.skill_resources cascade;
drop table if exists public.learning_resources cascade;
drop table if exists public.career_skills cascade;
drop table if exists public.skills cascade;
drop table if exists public.careers cascade;
drop table if exists public.categories cascade;
drop table if exists public.profiles cascade;

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text unique,
    full_name text not null default '',
    role text not null default 'student'
        check (role in ('student', 'faculty', 'admin', 'hod', 'placement_cell')),
    student_id text unique,
    department text not null default 'General',
    phone text,
    skills text[] not null default '{}',
    status text not null default 'pending'
        check (status in ('pending', 'active', 'rejected')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamptz not null default now()
);

create table public.careers (
    id uuid primary key default uuid_generate_v4(),
    title text not null unique,
    description text,
    industry text,
    average_salary numeric(12, 2),
    growth_outlook text,
    created_at timestamptz not null default now()
);

create table public.skills (
    id uuid primary key default uuid_generate_v4(),
    name text not null unique,
    category text,
    description text,
    created_at timestamptz not null default now()
);

create table public.career_skills (
    career_id uuid not null references public.careers(id) on delete cascade,
    skill_id uuid not null references public.skills(id) on delete cascade,
    required_level text not null
        check (required_level in ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
    primary key (career_id, skill_id)
);

create table public.learning_resources (
    id uuid primary key default uuid_generate_v4(),
    title text not null,
    url text not null,
    type text
        check (type in ('Course', 'Book', 'Video', 'Article', 'Project')),
    provider text,
    cost_type text check (cost_type in ('Free', 'Paid')),
    difficulty text,
    created_at timestamptz not null default now()
);

create table public.skill_resources (
    skill_id uuid not null references public.skills(id) on delete cascade,
    resource_id uuid not null references public.learning_resources(id) on delete cascade,
    primary key (skill_id, resource_id)
);

create table public.student_goals (
    id uuid primary key default uuid_generate_v4(),
    student_id uuid not null references public.profiles(id) on delete cascade,
    career_id uuid references public.careers(id) on delete set null,
    career_title text,
    status text not null default 'in_progress'
        check (status in ('in_progress', 'completed', 'abandoned')),
    target_date date,
    created_at timestamptz not null default now()
);

create table public.student_skills (
    student_id uuid not null references public.profiles(id) on delete cascade,
    skill_id uuid not null references public.skills(id) on delete cascade,
    current_level text not null
        check (current_level in ('Beginner', 'Intermediate', 'Advanced', 'Expert')),
    verified boolean not null default false,
    primary key (student_id, skill_id)
);

create table public.activities (
    id uuid primary key default uuid_generate_v4(),
    student_id uuid not null references public.profiles(id) on delete cascade,
    student_name text,
    student_reg_no text,
    department text not null default 'General',
    title text not null,
    category text not null,
    outcome_type text
        check (outcome_type in ('Technical', 'Research', 'Leadership', 'Sports')),
    skill_tag text,
    academic_year text,
    semester text,
    description text not null,
    date date not null,
    proof_url text,
    status text not null default 'pending'
        check (status in ('pending', 'approved', 'rejected')),
    reviewer_comment text,
    approved_by text,
    approved_at timestamptz,
    integrity_hash text unique,
    submitted_at timestamptz not null default now()
);

create table public.research_papers (
    id uuid primary key default uuid_generate_v4(),
    faculty_id uuid not null references public.profiles(id) on delete cascade,
    faculty_name text,
    title text not null,
    abstract text,
    publication_date date,
    journal_conference text,
    url text,
    created_at timestamptz not null default now()
);

create table public.courses (
    id uuid primary key default uuid_generate_v4(),
    student_id uuid not null references public.profiles(id) on delete cascade,
    course_name text not null,
    course_code text not null,
    credits integer not null default 0,
    semester text,
    status text not null default 'enrolled'
        check (status in ('enrolled', 'completed', 'verified')),
    grade text,
    created_at timestamptz not null default now()
);

create table public.semester_results (
    id uuid primary key default uuid_generate_v4(),
    student_id uuid not null references public.profiles(id) on delete cascade,
    semester text not null,
    subject text not null,
    subject_code text not null,
    credits integer not null default 0,
    marks numeric(6, 2) not null,
    max_marks numeric(6, 2) not null default 100,
    grade text not null,
    grade_points numeric(4, 2) not null,
    verification_status text not null default 'verified'
        check (verification_status in ('pending', 'verified', 'rejected')),
    verification_hash text unique,
    verified_by text,
    verified_at timestamptz,
    created_at timestamptz not null default now()
);

create table public.placement_drives (
    id uuid primary key default uuid_generate_v4(),
    company_name text not null,
    role_offered text not null,
    package_lpa numeric(6, 2) not null default 0,
    drive_date date not null,
    application_deadline date,
    eligibility_cgpa numeric(4, 2) not null default 0,
    eligible_departments text[] not null default '{}',
    required_skills text[] not null default '{}',
    openings integer not null default 1,
    status text not null default 'open'
        check (status in ('upcoming', 'open', 'closed', 'completed')),
    description text,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
);

create table public.placement_applications (
    id uuid primary key default uuid_generate_v4(),
    drive_id uuid not null references public.placement_drives(id) on delete cascade,
    student_id uuid not null references public.profiles(id) on delete cascade,
    status text not null default 'applied'
        check (status in ('applied', 'shortlisted', 'rejected', 'selected', 'withdrawn')),
    applied_at timestamptz not null default now(),
    unique (drive_id, student_id)
);

create table public.placement_notifications (
    id uuid primary key default uuid_generate_v4(),
    profile_id uuid not null references public.profiles(id) on delete cascade,
    drive_id uuid references public.placement_drives(id) on delete cascade,
    title text not null,
    message text not null,
    notification_type text not null default 'placement_drive',
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

create table public.aptitude_tests (
    id uuid primary key default uuid_generate_v4(),
    drive_id uuid unique references public.placement_drives(id) on delete cascade,
    title text not null,
    company_name text,
    description text,
    duration_minutes integer not null default 30,
    passing_score integer not null default 60,
    questions jsonb not null default '[]'::jsonb,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
);

create table public.aptitude_attempts (
    id uuid primary key default uuid_generate_v4(),
    test_id uuid not null references public.aptitude_tests(id) on delete cascade,
    student_id uuid not null references public.profiles(id) on delete cascade,
    score integer not null default 0,
    total_questions integer not null default 0,
    passed boolean not null default false,
    answers jsonb not null default '{}'::jsonb,
    submitted_at timestamptz not null default now()
);

create table public.audit_logs (
    id uuid primary key default uuid_generate_v4(),
    actor_id uuid references public.profiles(id) on delete set null,
    role text,
    action_type text not null,
    record_id text,
    details text,
    timestamp timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute procedure public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
    insert into public.profiles (
        id,
        email,
        full_name,
        role,
        student_id,
        department,
        status
    )
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data->>'full_name', ''),
        coalesce(new.raw_user_meta_data->>'role', 'student'),
        nullif(new.raw_user_meta_data->>'student_id', ''),
        coalesce(new.raw_user_meta_data->>'department', 'General'),
        'pending'
    )
    on conflict (id) do update
    set
        email = excluded.email,
        full_name = excluded.full_name,
        role = excluded.role,
        student_id = excluded.student_id,
        department = excluded.department;

    return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();

create or replace function public.seed_demo_account(
    p_user_id uuid,
    p_user_email text,
    p_user_password text,
    p_user_name text,
    p_user_role text,
    p_user_status text,
    p_user_student_id text,
    p_user_department text,
    p_user_phone text,
    p_user_skills text[]
)
returns void
language plpgsql
security definer
as $$
declare
    metadata jsonb;
begin
    metadata := jsonb_build_object(
        'full_name', p_user_name,
        'role', p_user_role,
        'student_id', p_user_student_id,
        'department', p_user_department
    );

    delete from auth.identities
    where user_id = p_user_id;

    delete from auth.users
    where id = p_user_id
       or email = p_user_email;

    insert into auth.users (
        id,
        instance_id,
        role,
        aud,
        email,
        raw_app_meta_data,
        raw_user_meta_data,
        is_super_admin,
        encrypted_password,
        created_at,
        updated_at,
        last_sign_in_at,
        email_confirmed_at,
        confirmation_sent_at,
        confirmation_token,
        recovery_token,
        email_change_token_new,
        email_change
    )
    values (
        p_user_id,
        '00000000-0000-0000-0000-000000000000',
        'authenticated',
        'authenticated',
        p_user_email,
        '{"provider":"email","providers":["email"]}'::jsonb,
        metadata,
        false,
        crypt(p_user_password, gen_salt('bf')),
        now(),
        now(),
        now(),
        now(),
        now(),
        '',
        '',
        '',
        ''
    );

    insert into auth.identities (
        id,
        provider_id,
        provider,
        user_id,
        identity_data,
        last_sign_in_at,
        created_at,
        updated_at
    )
    values (
        p_user_id,
        p_user_id::text,
        'email',
        p_user_id,
        jsonb_build_object(
            'sub', p_user_id::text,
            'email', p_user_email,
            'email_verified', true
        ),
        now(),
        now(),
        now()
    );

    update public.profiles
    set
        email = p_user_email,
        full_name = p_user_name,
        role = p_user_role,
        student_id = p_user_student_id,
        department = p_user_department,
        phone = p_user_phone,
        skills = p_user_skills,
        status = p_user_status
    where id = p_user_id;
end;
$$;

create or replace function public.is_role(role_names text[])
returns boolean
language sql
stable
security definer
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role = any(role_names)
    );
$$;

create or replace function public.guard_profile_updates()
returns trigger
language plpgsql
as $$
begin
    if auth.uid() = old.id and not public.is_role(array['admin']) then
        if new.role is distinct from old.role
            or new.status is distinct from old.status
            or new.email is distinct from old.email
            or new.student_id is distinct from old.student_id
            or new.department is distinct from old.department then
            raise exception 'You are not allowed to change protected profile fields.';
        end if;
    end if;

    return new;
end;
$$;

create trigger profiles_guard_updates
before update on public.profiles
for each row
execute procedure public.guard_profile_updates();

create or replace function public.notify_students_about_drive()
returns trigger
language plpgsql
security definer
as $$
begin
    insert into public.placement_notifications (
        profile_id,
        drive_id,
        title,
        message,
        notification_type
    )
    select
        profile.id,
        new.id,
        new.company_name || ' drive is live',
        new.role_offered || ' applications are now open. Apply before ' ||
            coalesce(to_char(new.application_deadline, 'DD Mon YYYY'), to_char(new.drive_date, 'DD Mon YYYY')) || '.',
        'placement_drive'
    from public.profiles profile
    where profile.role = 'student'
      and profile.status = 'active';

    return new;
end;
$$;

create trigger placement_drive_notifications
after insert on public.placement_drives
for each row
execute procedure public.notify_students_about_drive();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.careers enable row level security;
alter table public.skills enable row level security;
alter table public.career_skills enable row level security;
alter table public.learning_resources enable row level security;
alter table public.skill_resources enable row level security;
alter table public.student_goals enable row level security;
alter table public.student_skills enable row level security;
alter table public.activities enable row level security;
alter table public.research_papers enable row level security;
alter table public.courses enable row level security;
alter table public.semester_results enable row level security;
alter table public.placement_drives enable row level security;
alter table public.placement_applications enable row level security;
alter table public.placement_notifications enable row level security;
alter table public.aptitude_tests enable row level security;
alter table public.aptitude_attempts enable row level security;
alter table public.audit_logs enable row level security;

create policy "profiles_select"
on public.profiles
for select
using (
    status = 'active'
    or auth.uid() = id
    or public.is_role(array['admin', 'faculty', 'hod', 'placement_cell'])
);

create policy "profiles_update_self_or_admin"
on public.profiles
for update
using (
    auth.uid() = id
    or public.is_role(array['admin'])
)
with check (
    auth.uid() = id
    or public.is_role(array['admin'])
);

create policy "categories_select_all"
on public.categories
for select
using (true);

create policy "categories_insert_admin"
on public.categories
for insert
with check (public.is_role(array['admin']));

create policy "careers_select_all"
on public.careers
for select
using (true);

create policy "skills_select_all"
on public.skills
for select
using (true);

create policy "career_skills_select_all"
on public.career_skills
for select
using (true);

create policy "learning_resources_select_all"
on public.learning_resources
for select
using (true);

create policy "skill_resources_select_all"
on public.skill_resources
for select
using (true);

create policy "student_goals_manage_own"
on public.student_goals
for all
using (auth.uid() = student_id or public.is_role(array['admin']))
with check (auth.uid() = student_id or public.is_role(array['admin']));

create policy "student_skills_manage_own"
on public.student_skills
for all
using (auth.uid() = student_id or public.is_role(array['admin']))
with check (auth.uid() = student_id or public.is_role(array['admin']));

create policy "activities_select_visible"
on public.activities
for select
using (
    status = 'approved'
    or auth.uid() = student_id
    or public.is_role(array['admin', 'faculty', 'hod', 'placement_cell'])
);

create policy "activities_insert_own"
on public.activities
for insert
with check (auth.uid() = student_id);

create policy "activities_update_reviewers"
on public.activities
for update
using (public.is_role(array['admin', 'faculty']))
with check (public.is_role(array['admin', 'faculty']));

create policy "activities_delete_rejected"
on public.activities
for delete
using (
    (auth.uid() = student_id and status = 'rejected')
    or public.is_role(array['admin'])
);

create policy "research_papers_select_all"
on public.research_papers
for select
using (true);

create policy "research_papers_insert_faculty"
on public.research_papers
for insert
with check (auth.uid() = faculty_id and public.is_role(array['faculty', 'admin']));

create policy "courses_select_visible"
on public.courses
for select
using (auth.uid() = student_id or public.is_role(array['admin', 'faculty', 'hod', 'placement_cell']));

create policy "courses_manage_owner"
on public.courses
for all
using (auth.uid() = student_id or public.is_role(array['admin']))
with check (auth.uid() = student_id or public.is_role(array['admin']));

create policy "semester_results_select_visible"
on public.semester_results
for select
using (
    verification_status = 'verified'
    or auth.uid() = student_id
    or public.is_role(array['admin', 'faculty', 'hod', 'placement_cell'])
);

create policy "semester_results_insert_owner_or_admin"
on public.semester_results
for insert
with check (auth.uid() = student_id or public.is_role(array['admin', 'faculty']));

create policy "semester_results_update_reviewers"
on public.semester_results
for update
using (public.is_role(array['admin', 'faculty']))
with check (public.is_role(array['admin', 'faculty']));

create policy "placement_drives_select_all"
on public.placement_drives
for select
using (true);

create policy "placement_drives_manage_team"
on public.placement_drives
for all
using (public.is_role(array['admin', 'placement_cell']))
with check (public.is_role(array['admin', 'placement_cell']));

create policy "placement_applications_select_visible"
on public.placement_applications
for select
using (
    auth.uid() = student_id
    or public.is_role(array['admin', 'placement_cell'])
);

create policy "placement_applications_insert_students"
on public.placement_applications
for insert
with check (
    auth.uid() = student_id
    and public.is_role(array['student'])
);

create policy "placement_applications_update_team"
on public.placement_applications
for update
using (
    public.is_role(array['admin', 'placement_cell'])
    or auth.uid() = student_id
)
with check (
    public.is_role(array['admin', 'placement_cell'])
    or auth.uid() = student_id
);

create policy "placement_notifications_select_visible"
on public.placement_notifications
for select
using (
    auth.uid() = profile_id
    or public.is_role(array['admin', 'placement_cell'])
);

create policy "placement_notifications_insert_team"
on public.placement_notifications
for insert
with check (public.is_role(array['admin', 'placement_cell', 'faculty']));

create policy "placement_notifications_update_owner"
on public.placement_notifications
for update
using (auth.uid() = profile_id or public.is_role(array['admin', 'placement_cell']))
with check (auth.uid() = profile_id or public.is_role(array['admin', 'placement_cell']));

create policy "aptitude_tests_select_all"
on public.aptitude_tests
for select
using (true);

create policy "aptitude_tests_manage_team"
on public.aptitude_tests
for all
using (public.is_role(array['admin', 'placement_cell']))
with check (public.is_role(array['admin', 'placement_cell']));

create policy "aptitude_attempts_select_visible"
on public.aptitude_attempts
for select
using (
    auth.uid() = student_id
    or public.is_role(array['admin', 'placement_cell'])
);

create policy "aptitude_attempts_insert_student"
on public.aptitude_attempts
for insert
with check (auth.uid() = student_id);

create policy "audit_logs_select_admin"
on public.audit_logs
for select
using (public.is_role(array['admin']));

create policy "audit_logs_insert_authenticated"
on public.audit_logs
for insert
with check (auth.uid() is not null);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000001',
    'admin@vsarp.com',
    'password123',
    'VSARP Administrator',
    'admin',
    'active',
    null,
    'Administration',
    '9876500000',
    array[]::text[]
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000101',
    'aarav.sharma@vsarp.edu',
    'password123',
    'Aarav Sharma',
    'student',
    'active',
    'CS-2023-001',
    'Computer Science',
    '9876543210',
    array['Python', 'Machine Learning', 'SQL']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000102',
    'priya.patel@vsarp.edu',
    'password123',
    'Priya Patel',
    'student',
    'active',
    'CS-2023-002',
    'Computer Science',
    '9876543211',
    array['Java', 'Spring Boot', 'AWS']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000103',
    'rohan.deshmukh@vsarp.edu',
    'password123',
    'Rohan Deshmukh',
    'student',
    'active',
    'CS-2023-003',
    'Computer Science',
    '9876543212',
    array['Python', 'IoT', 'Data Structures']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000104',
    'sneha.kulkarni@vsarp.edu',
    'password123',
    'Sneha Kulkarni',
    'student',
    'active',
    'CS-2023-004',
    'Computer Science',
    '9876543213',
    array['React', 'Node.js', 'MongoDB']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000105',
    'arjun.mehta@vsarp.edu',
    'password123',
    'Arjun Mehta',
    'student',
    'active',
    'CS-2023-005',
    'Computer Science',
    '9876543214',
    array['Java', 'Data Structures', 'System Design']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000106',
    'neha.reddy@vsarp.edu',
    'password123',
    'Neha Reddy',
    'student',
    'active',
    'CS-2023-006',
    'Computer Science',
    '9876543215',
    array['Python', 'Data Visualization', 'SQL']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000107',
    'vikram.singh@vsarp.edu',
    'password123',
    'Vikram Singh',
    'student',
    'active',
    'CS-2023-007',
    'Computer Science',
    '9876543216',
    array['Cloud', 'DevOps', 'Linux']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000108',
    'kavya.menon@vsarp.edu',
    'password123',
    'Kavya Menon',
    'student',
    'active',
    'CS-2023-008',
    'Computer Science',
    '9876543217',
    array['Cybersecurity', 'Networking', 'Python']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000109',
    'ishaan.kapoor@vsarp.edu',
    'password123',
    'Ishaan Kapoor',
    'student',
    'active',
    'CS-2023-009',
    'Computer Science',
    '9876543218',
    array['JavaScript', 'React', 'UI Engineering']
);

select public.seed_demo_account(
    '00000000-0000-4000-8000-000000000110',
    'tanvi.rao@vsarp.edu',
    'password123',
    'Tanvi Rao',
    'student',
    'active',
    'CS-2023-010',
    'Computer Science',
    '9876543219',
    array['AI', 'NLP', 'Python']
);

insert into public.activities (
    id,
    student_id,
    student_name,
    student_reg_no,
    department,
    title,
    category,
    outcome_type,
    skill_tag,
    academic_year,
    semester,
    description,
    date,
    status,
    reviewer_comment,
    approved_by,
    approved_at,
    integrity_hash,
    submitted_at
)
values
    (
        '10000000-0000-4000-8000-000000000001',
        '00000000-0000-4000-8000-000000000101',
        'Aarav Sharma',
        'CS-2023-001',
        'Computer Science',
        'Smart India Hackathon - Winner',
        'Hackathon',
        'Technical',
        'Python, Problem Solving',
        '2025-2026',
        '5',
        'Led a 6-member team to build an AI-based crop disease detection system.',
        date '2026-01-17',
        'approved',
        'Strong technical submission with clear implementation evidence.',
        'Dr. Kavita Rao',
        timestamptz '2026-01-20 10:30:00+00',
        'activity_aarav_hackathon_2026',
        timestamptz '2026-01-18 09:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000002',
        '00000000-0000-4000-8000-000000000101',
        'Aarav Sharma',
        'CS-2023-001',
        'Computer Science',
        'AWS Solutions Architect Certification',
        'Certification',
        'Technical',
        'Cloud, AWS',
        '2025-2026',
        '5',
        'Cleared AWS SAA-C03 certification with hands-on architecture labs.',
        date '2026-02-08',
        'approved',
        'Credential verified against the shared certificate link.',
        'Dr. Kavita Rao',
        timestamptz '2026-02-10 08:45:00+00',
        'activity_aarav_aws_2026',
        timestamptz '2026-02-09 08:45:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000003',
        '00000000-0000-4000-8000-000000000102',
        'Priya Patel',
        'CS-2023-002',
        'Computer Science',
        'IEEE Paper - Blockchain in Healthcare',
        'Research Paper',
        'Research',
        'Blockchain, Research',
        '2025-2026',
        '5',
        'Published a paper on secure medical records at IEEE ICECA 2025.',
        date '2026-01-11',
        'approved',
        'Publication and author details were verified.',
        'Prof. Neha Pillai',
        timestamptz '2026-01-14 11:15:00+00',
        'activity_priya_ieee_2026',
        timestamptz '2026-01-12 10:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000004',
        '00000000-0000-4000-8000-000000000103',
        'Rohan Deshmukh',
        'CS-2023-003',
        'Computer Science',
        'AI Robotics Simulation Challenge',
        'Hackathon',
        'Technical',
        'Python, IoT',
        '2025-2026',
        '6',
        'Built a Python-based autonomous navigation simulator for agricultural monitoring robots.',
        date '2026-02-21',
        'approved',
        'Project demo and certificate matched the faculty record.',
        'Dr. Kavita Rao',
        timestamptz '2026-02-23 07:40:00+00',
        'activity_rohan_ai_robotics_2026',
        timestamptz '2026-02-21 15:10:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000005',
        '00000000-0000-4000-8000-000000000104',
        'Sneha Kulkarni',
        'CS-2023-004',
        'Computer Science',
        'Full-Stack Development Internship',
        'Internship',
        'Technical',
        'React, Node.js',
        '2025-2026',
        '6',
        'Built a customer dashboard using React and Node.js for a Bangalore startup.',
        date '2026-03-02',
        'approved',
        'Internship letter and mentor confirmation were verified.',
        'Dr. Kavita Rao',
        timestamptz '2026-03-04 09:20:00+00',
        'activity_sneha_fullstack_2026',
        timestamptz '2026-03-02 18:20:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000006',
        '00000000-0000-4000-8000-000000000105',
        'Arjun Mehta',
        'CS-2023-005',
        'Computer Science',
        'Algorithms Club Mentor',
        'Leadership',
        'Leadership',
        'Data Structures, Leadership',
        '2025-2026',
        '6',
        'Mentored juniors through weekly DSA practice labs and mock coding interviews.',
        date '2026-02-27',
        'approved',
        'Mentoring roster and faculty note were verified.',
        'Prof. Neha Pillai',
        timestamptz '2026-02-28 09:10:00+00',
        'activity_arjun_dsa_mentor_2026',
        timestamptz '2026-02-27 16:50:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000007',
        '00000000-0000-4000-8000-000000000106',
        'Neha Reddy',
        'CS-2023-006',
        'Computer Science',
        'Data Analytics Internship at Zoho',
        'Internship',
        'Technical',
        'SQL, Data Visualization',
        '2025-2026',
        '6',
        'Analyzed support ticket trends and built SQL dashboards for product operations.',
        date '2026-02-01',
        'approved',
        'Internship certificate and dashboard screenshots were verified.',
        'Dr. Kavita Rao',
        timestamptz '2026-02-03 10:30:00+00',
        'activity_neha_analytics_2026',
        timestamptz '2026-02-02 10:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000008',
        '00000000-0000-4000-8000-000000000107',
        'Vikram Singh',
        'CS-2023-007',
        'Computer Science',
        'DevOps Deployment Sprint',
        'Hackathon',
        'Technical',
        'DevOps, Cloud',
        '2025-2026',
        '6',
        'Built a CI/CD workflow with containerized deployment and monitoring.',
        date '2026-02-14',
        'approved',
        'Deployment logs and event certificate were verified.',
        'Prof. Neha Pillai',
        timestamptz '2026-02-16 10:30:00+00',
        'activity_vikram_devops_2026',
        timestamptz '2026-02-15 10:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000009',
        '00000000-0000-4000-8000-000000000108',
        'Kavya Menon',
        'CS-2023-008',
        'Computer Science',
        'Cybersecurity Capture The Flag Finalist',
        'Hackathon',
        'Technical',
        'Cybersecurity, Networking',
        '2025-2026',
        '6',
        'Reached the final round of a national CTF with web security and network forensics challenges.',
        date '2026-03-12',
        'approved',
        'Scoreboard screenshot and certificate were verified.',
        'Dr. Kavita Rao',
        timestamptz '2026-03-14 10:30:00+00',
        'activity_kavya_ctf_2026',
        timestamptz '2026-03-13 10:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000010',
        '00000000-0000-4000-8000-000000000109',
        'Ishaan Kapoor',
        'CS-2023-009',
        'Computer Science',
        'React UI Engineering Internship',
        'Internship',
        'Technical',
        'React, UI Engineering',
        '2025-2026',
        '6',
        'Implemented reusable React components and accessibility fixes for a SaaS dashboard.',
        date '2026-01-28',
        'approved',
        'Internship letter and code samples were verified.',
        'Prof. Neha Pillai',
        timestamptz '2026-01-30 10:30:00+00',
        'activity_ishaan_react_2026',
        timestamptz '2026-01-29 10:00:00+00'
    ),
    (
        '10000000-0000-4000-8000-000000000011',
        '00000000-0000-4000-8000-000000000110',
        'Tanvi Rao',
        'CS-2023-010',
        'Computer Science',
        'NLP Research Poster',
        'Research Paper',
        'Research',
        'NLP, Python',
        '2025-2026',
        '6',
        'Presented an NLP research poster on multilingual text classification for academic support chatbots.',
        date '2026-02-24',
        'approved',
        'Poster and faculty abstract were verified.',
        'Dr. Kavita Rao',
        timestamptz '2026-02-26 10:30:00+00',
        'activity_tanvi_nlp_2026',
        timestamptz '2026-02-25 10:00:00+00'
    );

insert into public.courses (
    id,
    student_id,
    course_name,
    course_code,
    credits,
    semester,
    status,
    grade,
    created_at
)
values
    ('20000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000101', 'Database Management Systems', 'CS302', 4, '5', 'completed', 'A', now()),
    ('20000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000101', 'Design and Analysis of Algorithms', 'CS303', 4, '5', 'completed', 'A+', now()),
    ('20000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000102', 'Cloud Infrastructure Basics', 'CS311', 3, '5', 'completed', 'A', now()),
    ('20000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000102', 'Modern Web Development', 'CS312', 4, '5', 'completed', 'A+', now()),
    ('20000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000103', 'Data Analytics for Intelligent Systems', 'CS321', 3, '6', 'completed', 'A', now()),
    ('20000000-0000-4000-8000-000000000006', '00000000-0000-4000-8000-000000000104', 'Full Stack Development', 'CS351', 4, '6', 'completed', 'A', now()),
    ('20000000-0000-4000-8000-000000000007', '00000000-0000-4000-8000-000000000105', 'Professional Communication', 'HS301', 2, '6', 'completed', 'A+', now()),
    ('20000000-0000-4000-8000-000000000008', '00000000-0000-4000-8000-000000000105', 'Cloud Service Management', 'CS341', 4, '6', 'completed', 'A', now()),
    ('20000000-0000-4000-8000-000000000009', '00000000-0000-4000-8000-000000000106', 'Data Mining', 'CS505', 4, '5', 'completed', 'A', now()),
    ('20000000-0000-4000-8000-000000000010', '00000000-0000-4000-8000-000000000107', 'Cloud Computing', 'CS506', 4, '5', 'completed', 'A', now()),
    ('20000000-0000-4000-8000-000000000011', '00000000-0000-4000-8000-000000000108', 'Network Security', 'CS507', 4, '5', 'completed', 'A', now()),
    ('20000000-0000-4000-8000-000000000012', '00000000-0000-4000-8000-000000000109', 'Human Computer Interaction', 'CS508', 3, '5', 'completed', 'A+', now()),
    ('20000000-0000-4000-8000-000000000013', '00000000-0000-4000-8000-000000000110', 'Natural Language Processing', 'CS509', 4, '5', 'completed', 'A+', now());

insert into public.semester_results (
    id,
    student_id,
    semester,
    subject,
    subject_code,
    credits,
    marks,
    max_marks,
    grade,
    grade_points,
    verification_status,
    verification_hash,
    verified_by,
    verified_at,
    created_at
)
values
    ('30000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000101', '5', 'Database Management Systems', 'CS302', 4, 91, 100, 'A+', 10, 'verified', 'result_aarav_dbms_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000101', '5', 'Computer Networks', 'CS304', 3, 84, 100, 'A', 9, 'verified', 'result_aarav_cn_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000101', '5', 'Probability and Statistics', 'MA301', 3, 80, 100, 'B+', 8, 'verified', 'result_aarav_stats_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000102', '5', 'Modern Web Development', 'CS312', 4, 88, 100, 'A', 9, 'verified', 'result_priya_web_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000102', '5', 'Cloud Infrastructure Basics', 'CS311', 3, 92, 100, 'A+', 10, 'verified', 'result_priya_cloud_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000006', '00000000-0000-4000-8000-000000000102', '5', 'Data Structures', 'CS201', 4, 78, 100, 'B+', 8, 'verified', 'result_priya_dsa_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000007', '00000000-0000-4000-8000-000000000103', '6', 'Artificial Intelligence', 'CS302', 4, 82, 100, 'A', 9, 'verified', 'result_rohan_ai_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000008', '00000000-0000-4000-8000-000000000103', '6', 'Data Analytics for Intelligent Systems', 'CS321', 3, 90, 100, 'A+', 10, 'verified', 'result_rohan_analytics_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000009', '00000000-0000-4000-8000-000000000103', '6', 'Professional Ethics', 'HS302', 2, 76, 100, 'B+', 8, 'verified', 'result_rohan_ethics_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000010', '00000000-0000-4000-8000-000000000104', '6', 'Full Stack Development', 'CS351', 4, 86, 100, 'A', 9, 'verified', 'result_kabir_fullstack_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000011', '00000000-0000-4000-8000-000000000104', '6', 'Operating Systems', 'CS305', 4, 81, 100, 'A', 9, 'verified', 'result_kabir_os_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000012', '00000000-0000-4000-8000-000000000105', '6', 'Professional Communication', 'HS301', 2, 95, 100, 'A+', 10, 'verified', 'result_arjun_comm_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000013', '00000000-0000-4000-8000-000000000105', '6', 'Cloud Service Management', 'CS341', 4, 87, 100, 'A', 9, 'verified', 'result_arjun_cloud_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000014', '00000000-0000-4000-8000-000000000106', '5', 'Data Mining', 'CS505', 4, 86, 100, 'A', 9, 'verified', 'result_neha_data_mining_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000015', '00000000-0000-4000-8000-000000000107', '5', 'Cloud Computing', 'CS506', 4, 84, 100, 'A', 9, 'verified', 'result_vikram_cloud_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000016', '00000000-0000-4000-8000-000000000108', '5', 'Network Security', 'CS507', 4, 89, 100, 'A', 9, 'verified', 'result_kavya_security_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000017', '00000000-0000-4000-8000-000000000109', '5', 'Human Computer Interaction', 'CS508', 3, 91, 100, 'A+', 10, 'verified', 'result_ishaan_hci_2026', 'Controller of Examinations', now(), now()),
    ('30000000-0000-4000-8000-000000000018', '00000000-0000-4000-8000-000000000110', '5', 'Natural Language Processing', 'CS509', 4, 93, 100, 'A+', 10, 'verified', 'result_tanvi_nlp_2026', 'Controller of Examinations', now(), now());

insert into public.placement_drives (
    id,
    company_name,
    role_offered,
    package_lpa,
    drive_date,
    application_deadline,
    eligibility_cgpa,
    eligible_departments,
    required_skills,
    openings,
    status,
    description
)
values
    (
        '40000000-0000-4000-8000-000000000001',
        'TCS',
        'Systems Engineer',
        3.60,
        date '2026-05-12',
        date '2026-04-18',
        6.50,
        array['Computer Science'],
        array['Communication', 'Problem Solving', 'SQL'],
        24,
        'open',
        'Campus hiring drive for systems engineers focused on programming fundamentals and aptitude readiness.'
    ),
    (
        '40000000-0000-4000-8000-000000000002',
        'Infosys',
        'Digital Specialist',
        6.20,
        date '2026-05-21',
        date '2026-04-24',
        7.00,
        array['Computer Science'],
        array['JavaScript', 'Cloud', 'Problem Solving'],
        18,
        'open',
        'Digital specialist role with a focus on web platforms, cloud basics, and structured problem solving.'
    ),
    (
        '40000000-0000-4000-8000-000000000003',
        'Wipro',
        'Project Engineer',
        4.50,
        date '2026-05-28',
        date '2026-05-02',
        6.00,
        array['Computer Science'],
        array['Python', 'Communication', 'SQL'],
        20,
        'upcoming',
        'Project engineer drive with an aptitude round and interview process for multidisciplinary teams.'
    );

insert into public.aptitude_tests (
    id,
    drive_id,
    title,
    company_name,
    description,
    duration_minutes,
    passing_score,
    questions
)
values
    (
        '50000000-0000-4000-8000-000000000001',
        '40000000-0000-4000-8000-000000000001',
        'TCS Aptitude Round',
        'TCS',
        'Timed aptitude practice covering logic, numeracy, and verbal reasoning.',
        30,
        60,
        '[
          {"id":"tcs_q1","question":"Aptitude tests are mainly used to assess reasoning and decision speed.","options":["True","False","Only coding speed","Only attendance"],"answer":0},
          {"id":"tcs_q2","question":"If 4 machines finish a task in 8 hours, how long will 8 similar machines take?","options":["2 hours","4 hours","8 hours","16 hours"],"answer":1},
          {"id":"tcs_q3","question":"Choose the best approach for a difficult question in a timed test.","options":["Spend all your time on it","Mark for review and continue","Close the test","Skip the section entirely"],"answer":1}
        ]'::jsonb
    ),
    (
        '50000000-0000-4000-8000-000000000002',
        '40000000-0000-4000-8000-000000000002',
        'Infosys Digital Specialist Aptitude',
        'Infosys',
        'Practice round covering logic, analytics, and quick reasoning.',
        35,
        60,
        '[
          {"id":"inf_q1","question":"Which skill is most relevant to a digital specialist role?","options":["JavaScript","Handwriting","Only attendance","Only sports"],"answer":0},
          {"id":"inf_q2","question":"What is the average of 6, 8, and 10?","options":["7","8","9","10"],"answer":1},
          {"id":"inf_q3","question":"Best pacing strategy for 30 questions in 30 minutes?","options":["One question per minute","Five minutes each","Solve only easy questions and stop","Ignore flagged questions"],"answer":0}
        ]'::jsonb
    ),
    (
        '50000000-0000-4000-8000-000000000003',
        '40000000-0000-4000-8000-000000000003',
        'Wipro Aptitude Challenge',
        'Wipro',
        'Core aptitude round to warm up before the live drive.',
        30,
        60,
        '[
          {"id":"wip_q1","question":"Which option best reflects good communication in interviews?","options":["Clear, concise answers","Very short one-word answers","No eye contact","Avoid examples"],"answer":0},
          {"id":"wip_q2","question":"A sequence doubles starting at 3. What is the fourth term?","options":["6","12","24","48"],"answer":2},
          {"id":"wip_q3","question":"Why do companies use aptitude tests?","options":["To assess reasoning and readiness","To test handwriting","To replace interviews entirely","To score social media"],"answer":0}
        ]'::jsonb
    );

insert into public.placement_applications (
    id,
    drive_id,
    student_id,
    status,
    applied_at
)
values
    ('60000000-0000-4000-8000-000000000001', '40000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000101', 'shortlisted', now() - interval '10 days'),
    ('60000000-0000-4000-8000-000000000002', '40000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000102', 'applied', now() - interval '7 days'),
    ('60000000-0000-4000-8000-000000000003', '40000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000103', 'selected', now() - interval '5 days'),
    ('60000000-0000-4000-8000-000000000004', '40000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000104', 'applied', now() - interval '2 days');

insert into public.aptitude_attempts (
    id,
    test_id,
    student_id,
    score,
    total_questions,
    passed,
    answers,
    submitted_at
)
values
    (
        '70000000-0000-4000-8000-000000000001',
        '50000000-0000-4000-8000-000000000001',
        '00000000-0000-4000-8000-000000000101',
        100,
        3,
        true,
        '{"tcs_q1":0,"tcs_q2":1,"tcs_q3":1}'::jsonb,
        now() - interval '6 days'
    ),
    (
        '70000000-0000-4000-8000-000000000002',
        '50000000-0000-4000-8000-000000000002',
        '00000000-0000-4000-8000-000000000102',
        67,
        3,
        true,
        '{"inf_q1":0,"inf_q2":1,"inf_q3":2}'::jsonb,
        now() - interval '4 days'
    ),
    (
        '70000000-0000-4000-8000-000000000003',
        '50000000-0000-4000-8000-000000000003',
        '00000000-0000-4000-8000-000000000104',
        33,
        3,
        false,
        '{"wip_q1":0,"wip_q2":0,"wip_q3":2}'::jsonb,
        now() - interval '1 day'
    ),
    (
        '70000000-0000-4000-8000-000000000004',
        '50000000-0000-4000-8000-000000000001',
        '00000000-0000-4000-8000-000000000106',
        88,
        3,
        true,
        '{"tcs_q1":0,"tcs_q2":1,"tcs_q3":1}'::jsonb,
        now() - interval '3 days'
    ),
    (
        '70000000-0000-4000-8000-000000000005',
        '50000000-0000-4000-8000-000000000002',
        '00000000-0000-4000-8000-000000000107',
        74,
        3,
        true,
        '{"inf_q1":0,"inf_q2":1,"inf_q3":0}'::jsonb,
        now() - interval '3 days'
    ),
    (
        '70000000-0000-4000-8000-000000000006',
        '50000000-0000-4000-8000-000000000003',
        '00000000-0000-4000-8000-000000000108',
        82,
        3,
        true,
        '{"wip_q1":0,"wip_q2":2,"wip_q3":0}'::jsonb,
        now() - interval '2 days'
    ),
    (
        '70000000-0000-4000-8000-000000000007',
        '50000000-0000-4000-8000-000000000001',
        '00000000-0000-4000-8000-000000000109',
        69,
        3,
        true,
        '{"tcs_q1":0,"tcs_q2":1,"tcs_q3":2}'::jsonb,
        now() - interval '2 days'
    ),
    (
        '70000000-0000-4000-8000-000000000008',
        '50000000-0000-4000-8000-000000000002',
        '00000000-0000-4000-8000-000000000110',
        90,
        3,
        true,
        '{"inf_q1":0,"inf_q2":1,"inf_q3":0}'::jsonb,
        now() - interval '1 day'
    );

insert into public.placement_notifications (
    id,
    profile_id,
    drive_id,
    title,
    message,
    notification_type,
    is_read,
    created_at
)
values
    (
        '80000000-0000-4000-8000-000000000001',
        '00000000-0000-4000-8000-000000000101',
        '40000000-0000-4000-8000-000000000001',
        'TCS shortlist published',
        'You have been shortlisted for the TCS systems engineer drive. Prepare for the next round.',
        'application_status',
        false,
        now() - interval '5 days'
    ),
    (
        '80000000-0000-4000-8000-000000000002',
        '00000000-0000-4000-8000-000000000103',
        '40000000-0000-4000-8000-000000000002',
        'Infosys final status',
        'Congratulations, you are marked as selected for the Infosys digital specialist role.',
        'application_status',
        false,
        now() - interval '3 days'
    );

insert into public.categories (name)
values
    ('Academic'),
    ('Sports'),
    ('Cultural'),
    ('Social Service'),
    ('Leadership'),
    ('Internship'),
    ('Certification'),
    ('Hackathon'),
    ('Research Paper'),
    ('Soft Skills Test');

insert into public.skills (name, category, description)
values
    ('Python', 'Technical', 'Programming for automation, analytics, and backend work'),
    ('JavaScript', 'Technical', 'Web application development and frontend logic'),
    ('SQL', 'Technical', 'Database querying and data modeling'),
    ('Communication', 'Soft', 'Clear written and verbal communication'),
    ('Problem Solving', 'Soft', 'Structured reasoning and analytical thinking'),
    ('Cloud', 'Tool', 'Cloud deployment and infrastructure basics'),
    ('Data Visualization', 'Technical', 'Presenting insights through charts and dashboards'),
    ('Leadership', 'Soft', 'Initiative, planning, and team coordination')
on conflict (name) do nothing;

insert into public.careers (title, description, industry, average_salary, growth_outlook)
values
    ('Software Developer', 'Build and maintain modern software systems.', 'Technology', 800000, 'High'),
    ('Data Analyst', 'Interpret operational data and produce business insights.', 'Data Science', 700000, 'Very High'),
    ('Product Manager', 'Drive product direction and cross-functional delivery.', 'Technology', 1200000, 'High'),
    ('Digital Marketing Specialist', 'Run multi-channel campaigns and optimize digital growth.', 'Marketing', 500000, 'Moderate')
on conflict (title) do nothing;

insert into public.learning_resources (title, url, type, provider, cost_type, difficulty)
values
    ('Python for Everybody', 'https://www.coursera.org/specializations/python', 'Course', 'Coursera', 'Paid', 'Beginner'),
    ('SQLBolt', 'https://sqlbolt.com', 'Course', 'SQLBolt', 'Free', 'Beginner'),
    ('Communication Foundations', 'https://www.linkedin.com/learning/', 'Course', 'LinkedIn Learning', 'Paid', 'Intermediate');

drop function if exists public.seed_demo_account(uuid, text, text, text, text, text, text, text, text, text[]);

commit;
