-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text check (role in ('student', 'faculty', 'admin')),
  student_id text,
  department text,
  status text default 'pending' check (status in ('pending', 'active', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (safe to run multiple times)
alter table public.profiles enable row level security;

-- Policies (Drop first to avoid exists error)
drop policy if exists "Public profiles are viewable by everyone" on profiles;
create policy "Public profiles are viewable by everyone" 
  on profiles for select using ( true );

drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile" 
  on profiles for update using ( auth.uid() = id );

-- 2. TRIGGER: Auto-create Profile on Signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role, student_id, department, status)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'role', 
    new.raw_user_meta_data->>'student_id', 
    new.raw_user_meta_data->>'department',
    'pending'
  )
  on conflict (id) do nothing; -- Handle conflict
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger first to avoid duplication error on 'create trigger'
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 3. ACTIVITIES TABLE
create table if not exists public.activities (
  id uuid default uuid_generate_v4() primary key,
  student_id uuid references public.profiles(id) not null,
  student_name text,
  student_reg_no text,
  title text not null,
  category text,
  description text,
  date date,
  proof_url text,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewer_comment text,
  approved_by text,
  approved_at timestamp with time zone,
  integrity_hash text,
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.activities enable row level security;

drop policy if exists "Students can see own activities" on activities;
create policy "Students can see own activities" 
  on activities for select using ( auth.uid() = student_id );

drop policy if exists "Faculty and Admin can see all activities" on activities;
create policy "Faculty and Admin can see all activities" 
  on activities for select using ( 
    exists ( select 1 from profiles where id = auth.uid() and role in ('faculty', 'admin') )
  );

drop policy if exists "Students can insert own activities" on activities;
create policy "Students can insert own activities" 
  on activities for insert with check ( auth.uid() = student_id );

drop policy if exists "Faculty/Admin can update activities" on activities;
create policy "Faculty/Admin can update activities" 
  on activities for update using ( 
    exists ( select 1 from profiles where id = auth.uid() and role in ('faculty', 'admin') )
  );


-- 4. CATEGORIES TABLE
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.categories enable row level security;

drop policy if exists "Everyone can view categories" on categories;
create policy "Everyone can view categories" 
  on categories for select using ( true );

drop policy if exists "Only Admins can insert categories" on categories;
create policy "Only Admins can insert categories" 
  on categories for insert with check ( 
    exists ( select 1 from profiles where id = auth.uid() and role = 'admin' )
  );

-- Seed Categories (Safe insert)
insert into public.categories (name) values 
('Academic'), ('Sports'), ('Cultural'), ('Social Service'), ('Leadership')
on conflict (name) do nothing;


-- 5. AUDIT LOGS TABLE
create table if not exists public.audit_logs (
  id uuid default uuid_generate_v4() primary key,
  actor_id uuid references public.profiles(id),
  role text,
  action_type text,
  record_id text,
  details text,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.audit_logs enable row level security;

drop policy if exists "Admins view all logs" on audit_logs;
create policy "Admins view all logs" 
  on audit_logs for select using ( 
    exists ( select 1 from profiles where id = auth.uid() and role = 'admin' )
  );

drop policy if exists "System/Users can insert logs" on audit_logs;
create policy "System/Users can insert logs" 
  on audit_logs for insert with check ( true );
